Repository Kernel360/hackathon2-loltfolio, pull requests merged in 2024-07, with the labels that each got.

#1 feat: yarn 설정 파일 생성 및 gitmessage.txt 생성
  .eslintrc.cjs
  .gitmessage.txt
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
Labels: feat

#4 [feat/#2] 디렉토리 생성
  src/apis/index.js
  src/components/common/index.js
  src/components/header/index.js
  src/components/page/index.js
  src/constants/index.js
  src/hooks/index.js
Labels: feat

#11 [feat/#10] feat: theme 구현, style lint 삭제
  .pnp.cjs
  .stylelintrc.json
  package.json
  src/main.jsx
  src/theme/GlobalStyle.jsx
  src/theme/index.js
  src/theme/theme.js
  yarn.lock
Labels: feat

#14 [feat/#13] feat: 폰트 적용
  public/fonts/NanumGothic-Regular.ttf
  src/index.css
Labels: feat

#17 [feat/#8] 유저 정보 컴포넌트 구현
  src/components/common/Flex.style.jsx
  src/components/userInfo/RoundPic.jsx
  src/components/userInfo/UserInfo.jsx
  src/components/userInfo/UserInfo.style.js
Labels: feat

#18 [feat/#3] 헤더 구현
  public/fonts/AbhayaLibre-SemiBold.ttf
  public/search.png
  src/components/common/Box.style.jsx
  src/components/common/Button.style.jsx
  src/components/common/Image.style.jsx
  src/components/common/Input.style.jsx
  src/components/common/Padding.jsx
  src/components/common/Text.style.jsx
  src/components/common/index.js
  src/components/header/Header.jsx
  src/components/header/index.js
  src/components/logo/Logo.jsx
  src/components/logo/index.js
  src/components/searchBar/SearchBar.jsx
  src/components/searchBar/index.js
  src/index.css
Labels: feat

#23 [Feat/#6] Achievement Component구현
  .eslintrc.cjs
  src/App.jsx
  src/components/achievement/AchievementCard.jsx
  src/components/achievement/AchievementContainer.jsx
  src/components/achievement/AchievementLabel.jsx
  src/components/achievement/AchievementWrapper.jsx
  src/components/achievement/index.js
  src/components/common/Card.style.jsx
  src/components/common/Margin.jsx
  src/components/common/Padding.jsx
  src/components/common/Text.style.jsx
  src/components/page/index.js
  src/theme/theme.js
Labels: feat

#26 design: SearchBar 너비 조정
  src/components/searchBar/SearchBar.jsx
Labels: design

#32 [feat/#29] index.html title 변경
  index.html
Labels: feat

#31 [refactor/#30] App.css 삭제에 따른 css 파일 import 변경
  src/App.jsx
Labels: refactor

#38 [Feat/#35] axios hook 생성
  src/apis/index.js
  src/hooks/index.js
  vite.config.js
Labels: feat
